name: pie-security-release
on: [workflow_dispatch, push]
jobs:
  pie-security-release:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: swapoff
      run: sudo swapoff /swapfile
    - name: cleanup
      run: sudo rm -rfv /swapfile /usr/src /usr/lib/jvm /home/linuxbrew /home/packer /root /usr/share/dotnet /usr/share/swift /usr/share/miniconda /usr/lib/google-cloud-sdk /var/lib/docker /usr/local /opt /home/runner/.*
    - name: mkdir
      run: sudo mkdir -pv /swapfile /usr/src /usr/lib/jvm /home/linuxbrew /home/packer /root /usr/share/dotnet /usr/share/swift /usr/share/miniconda /usr/lib/google-cloud-sdk /var/lib/docker /usr/local /opt
    - name: rm
      run: sudo rm -rfv .git
    - name: update
      run: sudo apt --yes --force-yes update
    - name: install
      run: sudo apt --yes --force-yes install --no-install-suggests --no-install-recommends repo
    - name: clean
      run: sudo apt --yes --force-yes clean
    - name: autoclean
      run: sudo apt --yes --force-yes autoclean
    - name: autoremove
      run: sudo apt --yes --force-yes autoremove
    - name: email
      run: sudo git config --global user.email "you@example.com"
    - name: name
      run: sudo git config --global user.name "Your Name"
    - name: chown
      run: sudo chown -Rv 0:0 ./
    - name: chmod
      run: sudo chmod -Rv 7777 ./
    - name: sh
      run: sudo ./pie-security-release.sh
    - name: manifest
      uses: actions/upload-artifact@v6
      with:
         name: pie-security-release.xml
         path: pie-security-release.xml
    - name: tar
      run: sudo tar --acls --selinux --xattrs -I "zstd --ultra -22 -v -T0 -r --format=zstd" -cvf pie-security-release.tar.zst ./pie-security-release/
    - name: upload
      uses: actions/upload-artifact@v6
      with:
         name: pie-security-release.tar.zst
         path: pie-security-release.tar.zst
